ansible_username: ec2-user
ansible_password: DevOps321
mongodb_host: mongodb-dev.dpavan.online
catalogue_host: catalogue-dev.dpavan.online
redis_host: redis-dev.dpavan.online
user_host: user-dev.dpavan.online
cart_host: cart-dev.dpavan.online
mysql_host: mysql-dev.dpavan.online
shipping_host: shipping-dev.dpavan.online

