- name: enable redis 7 version
  ansible.builtin.command: dnf module enable redis:7 -y 

- name: install redis
  ansible.builtin.dnf:
    name: redis
    state: present

- name: open redis to remote connections
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: "127.0.0.1"
    replace: "0.0.0.0"

- name: disable protected mode 
  ansible.builtin.lineinfile:
     path: /etc/redis/redis.conf
     regexp: "^protected-mode"
     line: "protected-mode no"

- name: start and enable redis
  ansible.builtin.redis:
    name: redis
    state: started
    enabled: true

     