- name: app set-up
  tags:
  - deployment
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup.yaml


- name: python set-up
  ansible.builtin.import_role:
   name: common
   tasks_from: python-setup.yaml


- name: systemd set-up
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd-setup.yaml

- name: start and enable payment service
  ansible.builtin.service:
    name: payment
    state: restarted
    enabled: yes