- name: copying rabbitmq repo
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: install rabbitmq server
  ansible.builtin.package:
    name: rabbitmq-server
    state: present

- name: start and enable rabbitmq
  ansible.builtin.service:
    name: rabbitmq
    state: started
    enabled: true

- name: create rabbitmq user
  community.rabbitmq.rabbitmq_user:
    user: "{{ user }}" 
    password: "{{ rabbitmq_password }}"
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: 